### ISSUE TITLE
Incomplete Iteration Plan

### ISSUE THREAD

**Issue by mapfap** [SSD2015/TeamTheFank#13]
Please also add your milestones and objectives to your [page](https://github.com/SSD2015/TeamTheFrank/wiki/Iteration-plan-EL1)

And I think it's better to create a file 'Iteration Plan EL1.md' and put it to your repo.

See this template.
https://github.com/SSD2015/219244/blob/master/Iteration%20Plan%20EL1.md

**Comment by thanachote-Frank** [comment]
@mapfap  I fixed them already. Please, Can you check them again ? and Is there anything else that I must fix?
