### ISSUE TITLE
Feedback on Iteration Plan EL1

### ISSUE THREAD

**Issue by mapfap** [SSD2015/TeamTheFank#14]
From [Iteration Plan](https://github.com/SSD2015/TeamTheFrank/blob/master/Iteration%20plan%20EL1.md),
- It looks good now.
- Fix: authenticate system -> authentication system 
- I think 'check username and password' is lower priority than creating the voting page. Voting has higher value to the project.

**Comment by thanachote-Frank** [comment]
I don't think so. Because it is just HTML templates. I think the function which the project can work. It is more important.

**Comment by dtinth** [comment]
I'm concerned about having to maintain 2 Play! applications: one for desktop and one for mobile… What are your rationale?

**Comment by thanachote-Frank** [comment]
I think it is too hard for us that we will create one site which supports desktop and mobile.
So, I think design separation is maybe easier. I'm not sure about that.

**Comment by thanachote-Frank** [comment]
I use Heroku for server. It can deploy automatically if we push a new code to Github. And I think if we use  two repositories, it can track clearly what have done. It also can create sub-domain for the website easily. I don't know that there are another ways. If there are another ways, please suggest us.

**Comment by dtinth** [comment]
Ah, I understand. Some questions:
- How do you make sure that the application logic is in sync with each other?
- How do you share database?
- Do you really want to have the mobile version and desktop version on different subdomain?

For creating a website that works with both mobile and desktop, you can learn about "Responsive Web Design." Some libraries such as [Bootstrap](http://getbootstrap.com/) makes this easy.

**Comment by thanachote-Frank** [comment]
- We don't have idea about that yet.
- We think it can share. If we set config in Heroku. Follow this link http://stackoverflow.com/questions/5981508/share-database-between-2-apps-in-heroku
- Here's the design of my group. 1st pic is desktop and 2nd is mobile. We don't have idea to make Responsive Web Design for my designs. Can you help me to make Responsive Web Design?
  ![Desktop](https://cloud.githubusercontent.com/assets/5871827/6369785/00dcf2ac-bd1c-11e4-8b73-bd62aa4ce533.jpg)
  ![Mobile](https://cloud.githubusercontent.com/assets/5871827/6369786/013e3986-bd1c-11e4-8742-9c194381f340.jpg)
